version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card_pilot_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 5173:5173
  server:
    image: nginx:latest
    container_name: card_pilot_server
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
  db:
    image: mariadb:10.7.8
    container_name: card_pilot_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306