name: Test application

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Copy env
        run: php -r "copy('.env.example', '.env');"
      - name: Install composer
        run: composer install -q --no-ansi --no-interacction --no-scripts --no-progress
      - name: Generate app key
        run: php artisan key:generate